name: ToteFullOfQueries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: PythonPath
        run: |
          export PYTHONPATH=$(pwd)

      - name: Install Dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate
          pip install -r ymlrequirements.txt

      - name: Audit Python Dependencies
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          virtual-environment: venv

      - name: Set AWS Region
        run: |
          echo "AWS_REGION=eu-west-2" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-west-2" >> $GITHUB_ENV
          
      - name: Auto-fix Formatting Issues
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          black src/ tests/ terraform/
          flake8 src/ tests/ terraform/  --max-line-length=100
          bandit -r src/ terraform/
          
      - name: Run Tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          # Run pytest with coverage and JUnit XML output.
          pytest tests/ --cov=src --cov-report=term-missing --junitxml=pytest.xml
          # Generate a plain text coverage report.
          coverage report > pytest-coverage.txt
          # Optionally, generate an XML coverage report if needed.
          coverage xml -o pytest-coverage.xml
          
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          # Use the text report for the coverage comment.
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Coverage Report
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          hide-comment: false
          xml-skip-covered: false
          report-only-changed-files: false
          create-new-comment: false
          default-branch: main
          remove-link-from-badge: false

  terraform:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Make Directory
        run : pip install -r requirements.txt -t deploy/layers/unzipped/dependencies/python

      - name: Configure AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-west-2" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        
