name: ToteFullOfQueries  

on: 
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"      

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python -m pip install .
      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          virtual-environment: env/
          
      - name: Set AWS Region
        run: |
          echo "AWS_REGION=eu-west-2" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-west-2" >> $GITHUB_ENV
          
      - name: Auto-fix Formatting Issues
        run: |
          source venv/bin/activate
          black src/ tests/
          flake 8 src/ tests/
          bandit -r src/ tests/

      - name: Run Tests
        run: |
          pytest tests/

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
